name: action-upload-release
description: A small GitHub Action to upload build artifacts to releases.

inputs:
  files:
    description: |-
      A list of files to upload. If a directory is specified, all files in the
      directory will be uploaded.
    required: true
  release-id:
    description: |-
      The release ID to upload to. This is optional if the event that triggered
      this action is a release event.
    default: ${{ github.event.release.id }}

runs:
  using: composite
  steps:
    # What does this even do? Why do I need it?
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - run: ./upload ${{ inputs.files }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_REPO: ${{ github.repository }}
        RELEASE_ID: ${{ github.event.release.id }}
      shell: bash
